name: dopp_env
channels:
  - defaults
  - noemicazzaniga
dependencies:
  - python=3.8
  - eurostat=1.1.1
  - pandas
  - scikit-learn
  - pytorch
  - seaborn
  - nltk
  - requests
  - beautifulsoup4
  - jupyter
  - ipykernel
  - openpyxl
  - pip:
      - transformers==4.2.0
      - wget
      - statsmodels
      - pycountry
      - pycountry_convert
